### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by lengyijun** [dtanzer/reactjs-jointjs-example#1]
could you tell me how to run it locally,such as 
npm run start?

**Comment by dtanzer** [comment]
Run

    npm install
    npm build:watch

and then just open index.html - It should be as easy as that.

**Comment by paszkowskiDamian** [comment]
I think that you have react, redux and other dependencies installed globally. It may cause some issues and it is not a good practice.

**Comment by AnupNaruto** [comment]
You forgot to include bundle.js file because of which i wasted a lot of time.
but now I am getting this error
"warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `StationsView`. See https://fb.me/react-warning-keys for more information.
    in Station (created by StationsView)
    in StationsView (created by Connect(StationsView))
    in Connect(StationsView) (created by MainSection)
    in MainSection (created by Connect(MainSection))
    in Connect(MainSection)
    in div
    in Provider"

Any idea???????
attaching a screenshot
![reactjs_jointjs](https://user-images.githubusercontent.com/30925883/33013186-216555ae-ce09-11e7-8794-f98450113364.PNG)

**Comment by dtanzer** [comment]
This is just a warning. Some components are rendered in a list, each of them should have a unique "key" property.
I ignored it for this talk, because it is "just" a performance issue: https://reactjs.org/docs/lists-and-keys.html

**Comment by dtanzer** [comment]
Also, bundle.js should actually be created by running "npm build", IIRC...

**Comment by AnupNaruto** [comment]
Because of this warning..... i'm still not able to see anything on screen when i click "Network" tab or "Plan Journey" tab. 
see the above screenshot it's empty. i captured this screenshot after clicking "Network" tab.

Also npm build:watch doesn't create this file. The work around was i created a blank "bundle.js" file and ran "npm build:watch" which in turn populated the "bundle.js" without any errors.
